'use client';

import { useState, useEffect, useCallback } from 'react';
import {
  getAdminStudents,
  getAdminBatches,
  createAdminStudent,
  toggleStudentStatus,
  resetStudentPassword,
  AdminStudentItem,
  AdminBatchItem,
} from '@/lib/api';

export default function AdminStudentsPage() {
  const [students, setStudents] = useState<AdminStudentItem[]>([]);
  const [batches, setBatches] = useState<AdminBatchItem[]>([]);
  const [loading, setLoading] = useState(true);

  // Filters
  const [selectedBatch, setSelectedBatch] = useState<string>('');
  const [selectedClass, setSelectedClass] = useState<string>('');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [statusFilter, setStatusFilter] = useState<'active' | 'inactive' | 'all'>('all');

  // Modals
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [oneTimePasswordModal, setOneTimePasswordModal] = useState<{
    isOpen: boolean;
    studentName?: string;
    username?: string;
    password?: string;
  } | null>(null);

  // Create Form State
  const [name, setName] = useState('');
  const [classLevel, setClassLevel] = useState<'XI' | 'XII'>('XI');
  const [batchId, setBatchId] = useState('');
  const [customPassword, setCustomPassword] = useState('');
  const [formError, setFormError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [actionSuccess, setActionSuccess] = useState<string | null>(null);

  const fetchStudents = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getAdminStudents({
        batchId: selectedBatch || undefined,
        class: selectedClass || undefined,
        status: statusFilter,
        search: searchQuery || undefined,
      });
      setStudents(res.students);
    } catch (e) {
      console.error('Failed to fetch students:', e);
    } finally {
      setLoading(false);
    }
  }, [selectedBatch, selectedClass, statusFilter, searchQuery]);

  useEffect(() => {
    async function initData() {
      const bList = await getAdminBatches(true);
      setBatches(bList);
      if (bList.length > 0) {
        setBatchId(bList[0].id);
      }
    }
    initData();
  }, []);

  useEffect(() => {
    fetchStudents();
  }, [fetchStudents]);

  const handleCreateStudent = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    if (!name.trim()) {
      setFormError('Student full name is required.');
      return;
    }
    if (!batchId) {
      setFormError('Please select a target batch.');
      return;
    }

    setIsSubmitting(true);
    try {
      const res = await createAdminStudent({
        name: name.trim(),
        class: classLevel,
        batchId,
        password: customPassword.trim() || undefined,
      });

      if (res.success && res.data) {
        setShowCreateModal(false);
        setName('');
        setCustomPassword('');
        setActionSuccess(`Student "${res.data.name}" enrolled! Username: @${res.data.username}`);

        // If password was auto-generated by backend, show one-time credentials modal
        if (res.data.initialPassword) {
          setOneTimePasswordModal({
            isOpen: true,
            studentName: res.data.name,
            username: res.data.username,
            password: res.data.initialPassword,
          });
        }
        fetchStudents();
      } else {
        setFormError(res.error || 'Failed to enroll student.');
      }
    } catch (err) {
      setFormError('Network error while enrolling student.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleToggleStatus = async (student: AdminStudentItem) => {
    const actionLabel = student.isActive ? 'Deactivate' : 'Reactivate';
    if (!confirm(`Are you sure you want to ${actionLabel.toLowerCase()} account for "${student.fullName}"?`)) {
      return;
    }

    const success = await toggleStudentStatus(student.id, student.isActive);
    if (success) {
      setActionSuccess(`Student "${student.fullName}" ${student.isActive ? 'deactivated' : 'reactivated'}.`);
      fetchStudents();
    } else {
      alert(`Failed to ${actionLabel.toLowerCase()} student.`);
    }
  };

  const handleResetPassword = async (student: AdminStudentItem) => {
    try {
      const res = await resetStudentPassword(student.id);
      if (res.success && res.data) {
        // Open one-time plaintext password modal
        setOneTimePasswordModal({
          isOpen: true,
          studentName: student.fullName,
          username: res.data.username,
          password: res.data.newPassword,
        });
      } else {
        alert(res.error || 'Failed to reset password.');
      }
    } catch (err) {
      alert('Network error while resetting password.');
    }
  };

  const closeOneTimePasswordModal = () => {
    // Security guarantee: clear state completely so password is wiped from React state / DOM
    setOneTimePasswordModal(null);
  };

  return (
    <div className="space-y-6 antialiased">
      {/* Page Header */}
      <div className="bg-white border border-[#0F1B3D]/10 rounded-xl p-6 sm:p-8 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <span className="text-xs font-mono font-bold text-[#E8B84A] uppercase tracking-wider block mb-1">
            Student Operations
          </span>
          <h1 className="font-display font-extrabold text-2xl sm:text-3xl text-[#0F1B3D]">
            Student Directory
          </h1>
          <p className="text-xs text-[#0F1B3D]/70 mt-1">
            Manage student credentials, batch assignments, and security resets for New Pi Classes.
          </p>
        </div>

        <button
          onClick={() => {
            setFormError(null);
            setShowCreateModal(true);
          }}
          className="px-4 py-2.5 rounded-lg bg-[#0F1B3D] text-white text-xs font-semibold hover:bg-[#0F1B3D]/90 transition-colors shadow-sm flex items-center gap-1.5"
        >
          <span>+</span>
          <span>Enroll New Student</span>
        </button>
      </div>

      {actionSuccess && (
        <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-mono flex items-center justify-between">
          <span>✓ {actionSuccess}</span>
          <button onClick={() => setActionSuccess(null)} className="text-emerald-600 hover:text-emerald-900">
            ✕
          </button>
        </div>
      )}

      {/* Filter Toolbar */}
      <div className="bg-white border border-[#0F1B3D]/10 rounded-xl p-4 shadow-sm flex flex-wrap items-center gap-3">
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Search by name or @username..."
          className="flex-1 min-w-[200px] bg-[#F7F7F5] border border-[#0F1B3D]/15 rounded-lg px-3.5 py-2 text-xs focus:outline-none focus:border-[#0F1B3D]"
        />

        <select
          value={selectedBatch}
          onChange={(e) => setSelectedBatch(e.target.value)}
          className="bg-[#F7F7F5] border border-[#0F1B3D]/15 rounded-lg px-3 py-2 text-xs focus:outline-none focus:border-[#0F1B3D]"
        >
          <option value="">All Batches</option>
          {batches.map((b) => (
            <option key={b.id} value={b.id}>
              {b.name} ({b.class} - {b.stream})
            </option>
          ))}
        </select>

        <select
          value={selectedClass}
          onChange={(e) => setSelectedClass(e.target.value)}
          className="bg-[#F7F7F5] border border-[#0F1B3D]/15 rounded-lg px-3 py-2 text-xs focus:outline-none focus:border-[#0F1B3D]"
        >
          <option value="">All Classes</option>
          <option value="XI">Class XI</option>
          <option value="XII">Class XII</option>
        </select>

        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value as any)}
          className="bg-[#F7F7F5] border border-[#0F1B3D]/15 rounded-lg px-3 py-2 text-xs focus:outline-none focus:border-[#0F1B3D]"
        >
          <option value="all">Status: All</option>
          <option value="active">Active Only</option>
          <option value="inactive">Inactive Only</option>
        </select>
      </div>

      {/* Student Directory Table */}
      <div className="bg-white border border-[#0F1B3D]/10 rounded-xl p-6 shadow-sm space-y-4">
        <div className="flex items-center justify-between border-b border-[#0F1B3D]/10 pb-4">
          <h2 className="font-display font-bold text-lg text-[#0F1B3D]">
            Student Directory ({students.length})
          </h2>
        </div>

        {loading ? (
          <div className="py-12 text-center font-mono text-xs text-[#0F1B3D]/60">
            Loading student records from database...
          </div>
        ) : students.length === 0 ? (
          <div className="py-12 text-center space-y-3">
            <span className="text-3xl block">🎓</span>
            <p className="font-display font-bold text-base text-[#0F1B3D]">No Students Found</p>
            <p className="text-xs text-[#0F1B3D]/60">Try adjusting your filters or click &quot;Enroll New Student&quot; to add a student.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-[#F7F7F5] border-b border-[#0F1B3D]/10 text-[#0F1B3D]/70 font-mono uppercase tracking-wider text-[11px]">
                <tr>
                  <th className="py-3 px-4">Full Name</th>
                  <th className="py-3 px-4">Backend @Username</th>
                  <th className="py-3 px-4">Class</th>
                  <th className="py-3 px-4">Status</th>
                  <th className="py-3 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#0F1B3D]/10 font-sans">
                {students.map((student) => (
                  <tr key={student.id} className="hover:bg-[#F7F7F5]/50 transition-colors">
                    <td className="py-3.5 px-4 font-display font-bold text-sm text-[#0F1B3D]">
                      {student.fullName}
                    </td>
                    <td className="py-3.5 px-4 font-mono font-bold text-[#0F1B3D]">
                      <span className="px-2 py-0.5 rounded bg-[#0F1B3D]/5 border border-[#0F1B3D]/15 text-[#0F1B3D]">
                        @{student.username}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 font-mono">
                      Class {student.class}
                    </td>
                    <td className="py-3.5 px-4 font-mono">
                      <span
                        className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-bold ${
                          student.isActive
                            ? 'bg-emerald-50 text-emerald-700 border border-emerald-200'
                            : 'bg-red-50 text-red-700 border border-red-200'
                        }`}
                      >
                        <span className={`w-1.5 h-1.5 rounded-full ${student.isActive ? 'bg-emerald-500' : 'bg-red-500'}`}></span>
                        {student.isActive ? 'Active' : 'Inactive'}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 text-right space-x-2">
                      <button
                        onClick={() => handleResetPassword(student)}
                        className="px-2.5 py-1 rounded text-[11px] font-semibold font-mono bg-amber-50 text-amber-800 hover:bg-amber-100 border border-amber-300 transition-colors"
                      >
                        🔑 Reset Password
                      </button>
                      <button
                        onClick={() => handleToggleStatus(student)}
                        className={`px-2.5 py-1 rounded text-[11px] font-semibold font-mono transition-colors ${
                          student.isActive
                            ? 'bg-red-50 text-red-700 hover:bg-red-100 border border-red-200'
                            : 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100 border border-emerald-200'
                        }`}
                      >
                        {student.isActive ? 'Deactivate' : 'Reactivate'}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Enroll Student Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 bg-[#0F1B3D]/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl border border-[#0F1B3D]/15 space-y-5 animate-in fade-in zoom-in-95 duration-150">
            <div className="flex items-center justify-between border-b border-[#0F1B3D]/10 pb-3">
              <h3 className="font-display font-bold text-lg text-[#0F1B3D]">
                Enroll New Student
              </h3>
              <button onClick={() => setShowCreateModal(false)} className="text-[#0F1B3D]/60 hover:text-[#0F1B3D] text-lg">
                ✕
              </button>
            </div>

            {formError && (
              <div className="p-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-xs font-mono">
                ⚠️ {formError}
              </div>
            )}

            <form onSubmit={handleCreateStudent} className="space-y-4 text-xs">
              <div>
                <label className="block font-mono font-semibold text-[#0F1B3D] mb-1">
                  Full Name *
                </label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="e.g. Rahul Sharma"
                  required
                  className="w-full bg-[#F7F7F5] border border-[#0F1B3D]/15 rounded-lg px-3.5 py-2 text-xs focus:outline-none focus:border-[#0F1B3D]"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-mono font-semibold text-[#0F1B3D] mb-1">
                    Class *
                  </label>
                  <select
                    value={classLevel}
                    onChange={(e) => setClassLevel(e.target.value as 'XI' | 'XII')}
                    className="w-full bg-[#F7F7F5] border border-[#0F1B3D]/15 rounded-lg px-3 py-2 text-xs focus:outline-none focus:border-[#0F1B3D]"
                  >
                    <option value="XI">Class XI</option>
                    <option value="XII">Class XII</option>
                  </select>
                </div>

                <div>
                  <label className="block font-mono font-semibold text-[#0F1B3D] mb-1">
                    Batch Assignment *
                  </label>
                  <select
                    value={batchId}
                    onChange={(e) => setBatchId(e.target.value)}
                    required
                    className="w-full bg-[#F7F7F5] border border-[#0F1B3D]/15 rounded-lg px-3 py-2 text-xs focus:outline-none focus:border-[#0F1B3D]"
                  >
                    <option value="" disabled>Select Batch</option>
                    {batches.filter((b) => b.isActive).map((b) => (
                      <option key={b.id} value={b.id}>
                        {b.name} ({b.stream})
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <div>
                <label className="block font-mono font-semibold text-[#0F1B3D] mb-1">
                  Initial Password (Optional)
                </label>
                <input
                  type="text"
                  value={customPassword}
                  onChange={(e) => setCustomPassword(e.target.value)}
                  placeholder="Leave blank for auto-generated secure password"
                  className="w-full bg-[#F7F7F5] border border-[#0F1B3D]/15 rounded-lg px-3.5 py-2 text-xs focus:outline-none focus:border-[#0F1B3D]"
                />
                <span className="text-[10px] text-[#0F1B3D]/50 font-mono mt-1 block">
                  Username is auto-generated by the backend (e.g., npcrahu2601)
                </span>
              </div>

              <div className="pt-3 flex items-center justify-end gap-2 border-t border-[#0F1B3D]/10">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="px-4 py-2 rounded-lg bg-[#F7F7F5] border border-[#0F1B3D]/15 text-[#0F1B3D] text-xs font-semibold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-4 py-2 rounded-lg bg-[#0F1B3D] text-white text-xs font-semibold hover:bg-[#0F1B3D]/90 disabled:opacity-50"
                >
                  {isSubmitting ? 'Enrolling...' : 'Enroll Student'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Security-Sensitive One-Time Plaintext Password Modal */}
      {oneTimePasswordModal?.isOpen && (
        <div className="fixed inset-0 z-50 bg-[#0F1B3D]/70 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-2xl border-2 border-[#E8B84A] space-y-5 animate-in fade-in zoom-in-95 duration-150">
            <div className="flex items-center space-x-3 border-b border-[#0F1B3D]/10 pb-3">
              <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center text-xl text-amber-800">
                🔑
              </div>
              <div>
                <h3 className="font-display font-bold text-base text-[#0F1B3D]">
                  One-Time Student Credentials
                </h3>
                <p className="text-[11px] text-amber-800 font-mono font-semibold">
                  SECURITY NOTICE: Disappears upon modal close
                </p>
              </div>
            </div>

            <div className="bg-[#F7F7F5] border border-[#0F1B3D]/15 rounded-xl p-4 space-y-3 font-mono text-xs">
              <div>
                <span className="text-[#0F1B3D]/60 text-[10px] uppercase tracking-wider block">Student Name</span>
                <span className="font-bold text-sm text-[#0F1B3D]">{oneTimePasswordModal.studentName}</span>
              </div>

              <div>
                <span className="text-[#0F1B3D]/60 text-[10px] uppercase tracking-wider block">Backend Generated @Username</span>
                <span className="font-extrabold text-sm text-[#0F1B3D] bg-amber-100 px-2 py-0.5 rounded">
                  @{oneTimePasswordModal.username}
                </span>
              </div>

              <div>
                <span className="text-[#0F1B3D]/60 text-[10px] uppercase tracking-wider block">One-Time Plaintext Password</span>
                <span className="font-extrabold text-sm text-emerald-700 bg-emerald-100 px-2.5 py-1 rounded block mt-0.5 border border-emerald-300">
                  {oneTimePasswordModal.password}
                </span>
              </div>
            </div>

            <p className="text-[11px] text-[#0F1B3D]/70 leading-relaxed">
              Please copy these credentials and share them directly with the student. Once you click &quot;Close & Clear State&quot;, this password cannot be retrieved again.
            </p>

            <div className="pt-2 flex items-center justify-between gap-3">
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(
                    `New Pi Classes Student Account:\nUsername: ${oneTimePasswordModal.username}\nPassword: ${oneTimePasswordModal.password}`
                  );
                  alert('Credentials copied to clipboard!');
                }}
                className="px-3.5 py-2 rounded-lg bg-[#E8B84A] text-[#0F1B3D] text-xs font-bold hover:bg-[#E8B84A]/90 transition-colors flex items-center gap-1.5"
              >
                <span>📋</span>
                <span>Copy Credentials</span>
              </button>

              <button
                type="button"
                onClick={closeOneTimePasswordModal}
                className="px-4 py-2 rounded-lg bg-[#0F1B3D] text-white text-xs font-semibold hover:bg-[#0F1B3D]/90 transition-colors"
              >
                Close & Clear State
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
